apiVersion: batch/v1
kind: Job
metadata:
  name: hubble-generate-certs-4a617efdba
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - image: quay.io/cybozu/cilium-certgen
        name: certgen
